name: trvdos-docs

channels:
  - conda-forge

dependencies:
  - python
  - pip

  # Build dependencies
  - gsl
  - pkg-config
  - cmake
  - ninja

  # Runtime dependencies
  - mdanalysis

  # Documentation
  - sphinx
  - mdanalysis-sphinx-theme>=1.0.1